<?php

/**
 * @file
 * Implements the module hooks.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function minfin_kamerstuk_theme($existing, $type, $theme, $path) {
  return [
    'functional-table' => [
      'variables' => [
        'table' => [],
      ],
    ],
    'kamerstuk' => [
      'variables' => [
        'html' => '',
        'title' => '',
        'keywords' => '',
        'page_title' => '',
      ],
    ],
    'kamerstuk_navigatie' => [
      'variables' => [
        'next' => NULL,
        'toc' => NULL,
        'prev' => NULL,
      ],
    ],
    'minfin_chapter_list' => [
      'variables' => [
        'items' => [],
        'prefix_text' => NULL,
        'suffix_text' => NULL,
      ],
    ],
    'minfin_chapter_list_isb' => [
      'variables' => [
        'items' => [],
        'prefix_text' => NULL,
        'suffix_text' => NULL,
      ],
    ],
    'minfin_notes' => [
      'variables' => [
        'notes' => [],
      ],
    ],
    'minfin_related' => [
      'variables' => [
        'pdfs' => [],
        'appendixes' => [],
        'dossiers' => [],
        'information' => [],
        'beleidsevaluatie_link' => NULL,
        'performance_information_links' => [],
        'policy_review_links' => [],
        'cbs_links' => [],
        'visual' => NULL,
      ],
    ],
    'minfin_related_anchor' => [
      'variables' => [
        'budget_table_id' => 0,
        'information' => [],
        'beleidsevaluatie_link' => NULL,
        'performance_information_links' => [],
        'policy_review_links' => [],
        'cbs_links' => [],
        'visual' => NULL,
      ],
    ],
    'minfin_toc' => [
      'variables' => [
        'items' => [],
        'appendix' => [],
      ],
    ],
    'table-header' => [],
  ];
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function minfin_kamerstuk_system_breadcrumb_alter(Breadcrumb &$breadcrumb) {
  $routeMatch = \Drupal::routeMatch();

  $routeName = $routeMatch->getRouteName();
  $routes = [
    'minfin.isb_memorie_van_toelichting.',
    'minfin.memorie_van_toelichting.',
    'minfin.jaarverslag.',
    'minfin.miljoenennota.',
    'minfin.financieel_jaarverslag.',
    'minfin.voorjaarsnota.',
    'minfin.najaarsnota.',
    'minfin.belastingplan_memorie_van_toelichting.',
    'minfin.belastingplan_voorstel_van_wet.',
    'minfin.belastingplan_staatsblad.',
  ];
  do {
    $addYear = (strpos($routeName, array_shift($routes)) === 0);
  } while (!$addYear && $routes);

  if ($addYear) {
    $year = $routeMatch->getParameter('year');
    $links = $breadcrumb->getlinks();
    $cacheability = CacheableMetadata::createFromObject($breadcrumb);

    $breadcrumb = new Breadcrumb();
    $breadcrumb->addLink(array_shift($links));
    $breadcrumb->addLink(Link::createFromRoute($year, 'minfin_general.year.' . $year));
    foreach ($links as $link) {
      $breadcrumb->addLink($link);
    }
    $breadcrumb->addCacheableDependency($cacheability);
  }
}
