<?php

/**
 * @file
 * Implements the module hooks.
 */

/**
 * Implements hook_theme().
 */
function minfin_beleidsevaluaties_theme($existing, $type, $theme, $path) {
  return [
    'beleidsevaluatie' => [
      'variables' => [
        'beleidsevaluatie' => [],
      ],
    ],
    'beleidsevaluatie_overview' => [
      'variables' => [
        'filters' => NULL,
        'table' => NULL,
        'pager' => NULL,
      ],
    ],
    'beleidsevaluatie_visual_block' => [
      'variables' => [
        'links' => [],
      ],
    ],
  ];
}
