<?php

/**
 * @file
 * Provides minfin_ckan module.
 */

/**
 * Implements hook_theme().
 */
function minfin_ckan_theme($existing, $type, $theme, $path) {
  return [
    'open_data' => [
      'variables' => [
        'content' => NULL,
        'banner' => NULL,
      ],
    ],
    'dataset' => [
      'variables' => [
        'activeDataset' => NULL,
        'datasets' => [],
      ],
    ],
    'open_data_items' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
  ];

}
